modelFileUrl: "https://github.com/olliehaigh/library_v2/blob/main/library.xml"
outputDirUrl: "https://github.com/olliehaigh/library_v2/blob/main/generated"
modelConfig:
  packageNames:
    typesPackage: "Types Folder"
    queriesPackage: "Interfaces"
  defaults:
    classDefaults:
      classActions:
        - CREATE
        - READ
      highInstanceCount: false
      implementNode: true
      immutable: false

dependencies:
  "Personal Details":
    modelFileUrl: "https://github.com/api-generation/personal-details/blob/main/generated/mtt-models/personal-details.json"
    version: "1.0.0"
  "Core Types":
    modelFileUrl: "https://github.com/api-generation/core-types/blob/main/generated/mtt-models/core-types.json"
    version: "1.0.0"
loader:
  configFileUrl: "https://github.com/api-generation/common-config/blob/main/config/loaders/ea-xmi/config.yaml"
  outputSubDir: "mtt-models"
generators:
  graphql:
    configFileUrl: "https://github.com/api-generation/common-config/blob/main/config/generators/graphql/config.yaml"
    outputSubDir: "specs/graphql"
  openapi:
    configFileUrl: "https://github.com/api-generation/common-config/blob/main/config/generators/openapi/config.yaml"
    outputSubDir: "specs/openapi"
  mkdocs:
    configFileUrl: "https://github.com/api-generation/common-config/blob/main/config/generators/mkdoc/config.yaml"
    outputSubDir: "docs/mkdocs"
